In [27]:
import pandas as pd

df = pd.read_csv(
    filepath_or_buffer='/Users/mattsmacbook/Downloads/clean2.data', 
    header=None, 
    sep=',')

In [28]:
df.dropna(how="all", inplace=True) # drops the empty line at file-end

df.tail()


<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>0</th>
      <th>1</th>
      <th>2</th>
      <th>3</th>
      <th>4</th>
      <th>5</th>
      <th>6</th>
      <th>7</th>
      <th>8</th>
      <th>9</th>
      <th>...</th>
      <th>159</th>
      <th>160</th>
      <th>161</th>
      <th>162</th>
      <th>163</th>
      <th>164</th>
      <th>165</th>
      <th>166</th>
      <th>167</th>
      <th>168</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>6593</th>
      <td>NON-MUSK-jp13</td>
      <td>jp13_2+5</td>
      <td>51</td>
      <td>-123</td>
      <td>-23</td>
      <td>-108</td>
      <td>-117</td>
      <td>134</td>
      <td>-160</td>
      <td>82</td>
      <td>...</td>
      <td>-66</td>
      <td>164</td>
      <td>-14</td>
      <td>-29</td>
      <td>107</td>
      <td>171</td>
      <td>-44</td>
      <td>-115</td>
      <td>118</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>6594</th>
      <td>NON-MUSK-jp13</td>
      <td>jp13_2+6</td>
      <td>44</td>
      <td>-104</td>
      <td>-19</td>
      <td>-105</td>
      <td>-117</td>
      <td>142</td>
      <td>-165</td>
      <td>68</td>
      <td>...</td>
      <td>-51</td>
      <td>166</td>
      <td>-9</td>
      <td>150</td>
      <td>129</td>
      <td>158</td>
      <td>-66</td>
      <td>-144</td>
      <td>-5</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>6595</th>
      <td>NON-MUSK-jp13</td>
      <td>jp13_2+7</td>
      <td>44</td>
      <td>-102</td>
      <td>-19</td>
      <td>-104</td>
      <td>-117</td>
      <td>72</td>
      <td>-165</td>
      <td>65</td>
      <td>...</td>
      <td>90</td>
      <td>117</td>
      <td>-8</td>
      <td>150</td>
      <td>130</td>
      <td>159</td>
      <td>-66</td>
      <td>-144</td>
      <td>-6</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>6596</th>
      <td>NON-MUSK-jp13</td>
      <td>jp13_2+8</td>
      <td>51</td>
      <td>-121</td>
      <td>-23</td>
      <td>-106</td>
      <td>-117</td>
      <td>63</td>
      <td>-161</td>
      <td>79</td>
      <td>...</td>
      <td>86</td>
      <td>99</td>
      <td>-14</td>
      <td>-31</td>
      <td>106</td>
      <td>171</td>
      <td>-44</td>
      <td>-116</td>
      <td>117</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>6597</th>
      <td>NON-MUSK-jp13</td>
      <td>jp13_2+9</td>
      <td>51</td>
      <td>-122</td>
      <td>-23</td>
      <td>-106</td>
      <td>-117</td>
      <td>190</td>
      <td>-161</td>
      <td>80</td>
      <td>...</td>
      <td>40</td>
      <td>124</td>
      <td>-14</td>
      <td>-30</td>
      <td>107</td>
      <td>171</td>
      <td>-44</td>
      <td>-115</td>
      <td>118</td>
      <td>0.0</td>
    </tr>
  </tbody>
</table>
<p>5 rows × 169 columns</p>
</div>

In [29]:
df

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>0</th>
      <th>1</th>
      <th>2</th>
      <th>3</th>
      <th>4</th>
      <th>5</th>
      <th>6</th>
      <th>7</th>
      <th>8</th>
      <th>9</th>
      <th>...</th>
      <th>159</th>
      <th>160</th>
      <th>161</th>
      <th>162</th>
      <th>163</th>
      <th>164</th>
      <th>165</th>
      <th>166</th>
      <th>167</th>
      <th>168</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>MUSK-211</td>
      <td>211_1+1</td>
      <td>46</td>
      <td>-108</td>
      <td>-60</td>
      <td>-69</td>
      <td>-117</td>
      <td>49</td>
      <td>38</td>
      <td>-161</td>
      <td>...</td>
      <td>-308</td>
      <td>52</td>
      <td>-7</td>
      <td>39</td>
      <td>126</td>
      <td>156</td>
      <td>-50</td>
      <td>-112</td>
      <td>96</td>
      <td>1.0</td>
    </tr>
    <tr>
      <th>1</th>
      <td>MUSK-211</td>
      <td>211_1+10</td>
      <td>41</td>
      <td>-188</td>
      <td>-145</td>
      <td>22</td>
      <td>-117</td>
      <td>-6</td>
      <td>57</td>
      <td>-171</td>
      <td>...</td>
      <td>-59</td>
      <td>-2</td>
      <td>52</td>
      <td>103</td>
      <td>136</td>
      <td>169</td>
      <td>-61</td>
      <td>-136</td>
      <td>79</td>
      <td>1.0</td>
    </tr>
    <tr>
      <th>2</th>
      <td>MUSK-211</td>
      <td>211_1+11</td>
      <td>46</td>
      <td>-194</td>
      <td>-145</td>
      <td>28</td>
      <td>-117</td>
      <td>73</td>
      <td>57</td>
      <td>-168</td>
      <td>...</td>
      <td>-134</td>
      <td>-154</td>
      <td>57</td>
      <td>143</td>
      <td>142</td>
      <td>165</td>
      <td>-67</td>
      <td>-145</td>
      <td>39</td>
      <td>1.0</td>
    </tr>
    <tr>
      <th>3</th>
      <td>MUSK-211</td>
      <td>211_1+12</td>
      <td>41</td>
      <td>-188</td>
      <td>-145</td>
      <td>22</td>
      <td>-117</td>
      <td>-7</td>
      <td>57</td>
      <td>-170</td>
      <td>...</td>
      <td>-60</td>
      <td>-4</td>
      <td>52</td>
      <td>104</td>
      <td>136</td>
      <td>168</td>
      <td>-60</td>
      <td>-135</td>
      <td>80</td>
      <td>1.0</td>
    </tr>
    <tr>
      <th>4</th>
      <td>MUSK-211</td>
      <td>211_1+13</td>
      <td>41</td>
      <td>-188</td>
      <td>-145</td>
      <td>22</td>
      <td>-117</td>
      <td>-7</td>
      <td>57</td>
      <td>-170</td>
      <td>...</td>
      <td>-60</td>
      <td>-4</td>
      <td>52</td>
      <td>104</td>
      <td>137</td>
      <td>168</td>
      <td>-60</td>
      <td>-135</td>
      <td>80</td>
      <td>1.0</td>
    </tr>
    <tr>
      <th>5</th>
      <td>MUSK-211</td>
      <td>211_1+14</td>
      <td>46</td>
      <td>-194</td>
      <td>-145</td>
      <td>28</td>
      <td>-117</td>
      <td>72</td>
      <td>57</td>
      <td>-168</td>
      <td>...</td>
      <td>-138</td>
      <td>-156</td>
      <td>56</td>
      <td>143</td>
      <td>142</td>
      <td>164</td>
      <td>-67</td>
      <td>-145</td>
      <td>40</td>
      <td>1.0</td>
    </tr>
    <tr>
      <th>6</th>
      <td>MUSK-211</td>
      <td>211_1+15</td>
      <td>47</td>
      <td>-199</td>
      <td>-106</td>
      <td>28</td>
      <td>-117</td>
      <td>73</td>
      <td>27</td>
      <td>-104</td>
      <td>...</td>
      <td>-133</td>
      <td>-153</td>
      <td>55</td>
      <td>144</td>
      <td>142</td>
      <td>165</td>
      <td>-68</td>
      <td>-145</td>
      <td>37</td>
      <td>1.0</td>
    </tr>
    <tr>
      <th>7</th>
      <td>MUSK-211</td>
      <td>211_1+16</td>
      <td>41</td>
      <td>-199</td>
      <td>-101</td>
      <td>22</t

In [30]:
import numpy as np
df = pd.DataFrame(np.random.randn(150, 5), columns=list('01234'))

In [31]:
df

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>0</th>
      <th>1</th>
      <th>2</th>
      <th>3</th>
      <th>4</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>-1.095914</td>
      <td>-1.551469</td>
      <td>0.981895</td>
      <td>-0.432870</td>
      <td>-1.411340</td>
    </tr>
    <tr>
      <th>1</th>
      <td>0.469964</td>
      <td>-1.166556</td>
      <td>-2.232137</td>
      <td>0.586805</td>
      <td>0.217901</td>
    </tr>
    <tr>
      <th>2</th>
      <td>0.953652</td>
      <td>1.517304</td>
      <td>-1.791164</td>
      <td>-0.613101</td>
      <td>-0.737542</td>
    </tr>
    <tr>
      <th>3</th>
      <td>2.064038</td>
      <td>-0.601777</td>
      <td>1.679032</td>
      <td>-0.383737</td>
      <td>0.450195</td>
    </tr>
    <tr>
      <th>4</th>
      <td>-0.506759</td>
      <td>1.416161</td>
      <td>-0.210587</td>
      <td>-0.974258</td>
      <td>-0.598301</td>
    </tr>
    <tr>
      <th>5</th>
      <td>0.642621</td>
      <td>-0.546306</td>
      <td>-1.218114</td>
      <td>1.409158</td>
      <td>0.741128</td>
    </tr>
    <tr>
      <th>6</th>
      <td>-0.453286</td>
      <td>-0.637167</td>
      <td>-0.192942</td>
      <td>-2.792274</td>
      <td>0.893092</td>
    </tr>
    <tr>
      <th>7</th>
      <td>-0.391821</td>
      <td>0.436898</td>
      <td>1.069352</td>
      <td>0.353749</td>
      <td>0.696253</td>
    </tr>
    <tr>
      <th>8</th>
      <td>0.694607</td>
      <td>-0.005474</td>
      <td>-0.719470</td>
      <td>-0.439744</td>
      <td>0.602034</td>
    </tr>
    <tr>
      <th>9</th>
      <td>0.418970</td>
      <td>-0.600017</td>
      <td>2.045243</td>
      <td>1.739622</td>
      <td>0.083879</td>
    </tr>
    <tr>
      <th>10</th>
      <td>0.440519</td>
      <td>-0.004952</td>
      <td>2.241015</td>
      <td>-1.271302</td>
      <td>1.194618</td>
    </tr>
    <tr>
      <th>11</th>
      <td>2.455235</td>
      <td>-0.539465</td>
      <td>-2.735268</td>
      <td>-0.351351</td>
      <td>-0.203258</td>
    </tr>
    <tr>
      <th>12</th>
      <td>2.530214</td>
      <td>-0.665946</td>
      <td>1.825494</td>
      <td>-0.836948</td>
      <td>1.076873</td>
    </tr>
    <tr>
      <th>13</th>
      <td>-0.255127</td>
      <td>-1.655570</td>
      <td>-0.214720</td>
      <td>-0.086213</td>
      <td>-0.859774</td>
    </tr>
    <tr>
      <th>14</th>
      <td>-2.078945</td>
      <td>-1.188463</td>
      <td>0.713296</td>
      <td>1.320536</td>
      <td>0.154802</td>
    </tr>
    <tr>
      <th>15</th>
      <td>-0.142475</td>
      <td>-0.641034</td>
      <td>-2.216689</td>
      <td>0.202369</td>
      <td>-1.034165</td>
    </tr>
    <tr>
      <th>16</th>
      <td>-0.161296</td>
      <td>0.477008</td>
      <td>-1.153519</td>
      <td>0.704698</td>
      <td>0.209518</td>
    </tr>
    <tr>
      <th>17</th>
      <td>0.073049</td>
      <td>-1.235931</td>
      <td>0.452207</td>
      <td>0.561115</td>
      <td>-1.322129</td>
    </tr>
    <tr>
      <th>18</th>
      <td>-2.329896</td>
      <td>-1.416831</td>
      <td>0.960310</td>
      <td>-0.318211</td>
      <td>-0.481052</td>
    </tr>
    <tr>
      <th>19</th>
      <td>1.021334</td>
      <td>-0.367338</td>
      <td>-1.150722</td>
      <td>0.482677</td>
      <td>1.138936</td>
    </tr>
    <tr>
      <th>20</th>
      <td>1.246320</td>
      <td>-1.357321</td>
      <td>0.008276</td>
      <td>0.332444</td>
      <td>-0.982384</td>
    </tr>
    <tr>
      <th>21</th>
      <td>-0.667523</td>
      <td>0.348971</td>
      <td>-0.152877</td>
      <td>0.980034</td>
      <td>1.031978</td>
    </tr>
    <tr>
      <th>22</th>
      <td>0.118837</

In [32]:
X = df.ix[:,0:4].values
y = df.ix[:,4].values

/Users/mattsmacbook/Library/Python/2.7/lib/python/site-packages/ipykernel_launcher.py:1: DeprecationWarning:


.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated

/Users/mattsmacbook/Library/Python/2.7/lib/python/site-packages/ipykernel_launcher.py:2: DeprecationWarning:


.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated



In [33]:
import plotly.plotly as py
from plotly.graph_objs import *
import plotly.tools as tls

In [34]:
traces = []

legend = {0:False, 1:False, 2:False, 3:True}

colors = {'Iris-setosa': 'rgb(31, 119, 180)', 
          'Iris-versicolor': 'rgb(255, 127, 14)', 
          'Iris-virginica': 'rgb(44, 160, 44)'}

for col in range(4):
    for key in colors:
        traces.append(Histogram(x=X[y==key, col], 
                        opacity=0.75,
                        xaxis='x%s' %(col+1),
                        marker=Marker(color=colors[key]),
                        name=key,
                        showlegend=legend[col]))

data = Data(traces)

layout = Layout(barmode='overlay',
                xaxis=XAxis(domain=[0, 0.25], title='sepal length (cm)'),
                xaxis2=XAxis(domain=[0.3, 0.5], title='sepal width (cm)'),
                xaxis3=XAxis(domain=[0.55, 0.75], title='petal length (cm)'),
                xaxis4=XAxis(domain=[0.8, 1], title='petal width (cm)'),
                yaxis=YAxis(title='count'),
                title='Distribution of the different Iris flower features')

fig = Figure(data=data, layout=layout)
py.iplot(fig)

/Users/mattsmacbook/Library/Python/2.7/lib/python/site-packages/ipykernel_launcher.py:11: FutureWarning:

elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison



<iframe id="igraph" scrolling="no" style="border:none;" seamless="seamless" src="https://plot.ly/~Mdipietro1990/33.embed" height="525px" width="100%"></iframe>

In [35]:
from sklearn.preprocessing import StandardScaler
X_std = StandardScaler().fit_transform(X)

In [36]:
import numpy as np
mean_vec = np.mean(X_std, axis=0)
cov_mat = (X_std - mean_vec).T.dot((X_std - mean_vec)) / (X_std.shape[0]-1)
print('Covariance matrix \n%s' %cov_mat)

Covariance matrix 
[[ 1.00671141  0.04752149  0.00410932  0.04344737]
 [ 0.04752149  1.00671141  0.01525889 -0.06577866]
 [ 0.00410932  0.01525889  1.00671141  0.06351407]
 [ 0.04344737 -0.06577866  0.06351407  1.00671141]]


In [37]:
print('NumPy covariance matrix: \n%s' %np.cov(X_std.T))

NumPy covariance matrix: 
[[ 1.00671141  0.04752149  0.00410932  0.04344737]
 [ 0.04752149  1.00671141  0.01525889 -0.06577866]
 [ 0.00410932  0.01525889  1.00671141  0.06351407]
 [ 0.04344737 -0.06577866  0.06351407  1.00671141]]


In [38]:
cov_mat = np.cov(X_std.T)

eig_vals, eig_vecs = np.linalg.eig(cov_mat)

print('Eigenvectors \n%s' %eig_vecs)
print('\nEigenvalues \n%s' %eig_vals)

Eigenvectors 
[[-0.41615203  0.58475275  0.66868982  0.19425661]
 [ 0.54058273 -0.28332714  0.69474323 -0.38056258]
 [-0.37552154 -0.73554135  0.26490302  0.49778397]
 [ 0.62735267  0.19175209  0.00348642  0.75475003]]

Eigenvalues 
[0.8831917  0.99276436 1.05793886 1.09295072]


In [39]:
cor_mat1 = np.corrcoef(X_std.T)

eig_vals, eig_vecs = np.linalg.eig(cor_mat1)

print('Eigenvectors \n%s' %eig_vecs)
print('\nEigenvalues \n%s' %eig_vals)

Eigenvectors 
[[-0.41615203  0.58475275  0.66868982  0.19425661]
 [ 0.54058273 -0.28332714  0.69474323 -0.38056258]
 [-0.37552154 -0.73554135  0.26490302  0.49778397]
 [ 0.62735267  0.19175209  0.00348642  0.75475003]]

Eigenvalues 
[0.87730375 0.98614593 1.05088594 1.08566438]


In [40]:
cor_mat2 = np.corrcoef(X.T)

eig_vals, eig_vecs = np.linalg.eig(cor_mat2)

print('Eigenvectors \n%s' %eig_vecs)
print('\nEigenvalues \n%s' %eig_vals)

Eigenvectors 
[[-0.41615203  0.58475275  0.66868982  0.19425661]
 [ 0.54058273 -0.28332714  0.69474323 -0.38056258]
 [-0.37552154 -0.73554135  0.26490302  0.49778397]
 [ 0.62735267  0.19175209  0.00348642  0.75475003]]

Eigenvalues 
[0.87730375 0.98614593 1.05088594 1.08566438]


In [41]:
u,s,v = np.linalg.svd(X_std.T)
u

array([[ 0.19425661,  0.66868982, -0.58475275, -0.41615203],
       [-0.38056258,  0.69474323,  0.28332714,  0.54058273],
       [ 0.49778397,  0.26490302,  0.73554135, -0.37552154],
       [ 0.75475003,  0.00348642, -0.19175209,  0.62735267]])

In [42]:
for ev in eig_vecs:
    np.testing.assert_array_almost_equal(1.0, np.linalg.norm(ev))

In [43]:
# Make a list of (eigenvalue, eigenvector) tuples
eig_pairs = [(np.abs(eig_vals[i]), eig_vecs[:,i]) for i in range(len(eig_vals))]

# Sort the (eigenvalue, eigenvector) tuples from high to low
eig_pairs.sort()
eig_pairs.reverse()

# Visually confirm that the list is correctly sorted by decreasing eigenvalues
print('Eigenvalues in descending order:')
for i in eig_pairs:
    print(i[0])

Eigenvalues in descending order:
1.0856643814229832
1.0508859379208375
0.9861459288521288
0.8773037518040496


In [44]:
tot = sum(eig_vals)
var_exp = [(i / tot)*100 for i in sorted(eig_vals, reverse=True)]
cum_var_exp = np.cumsum(var_exp)

trace1 = Bar(
        x=['PC %s' %i for i in range(1,5)],
        y=var_exp,
        showlegend=False)

trace2 = Scatter(
        x=['PC %s' %i for i in range(1,5)], 
        y=cum_var_exp,
        name='cumulative explained variance')

data = Data([trace1, trace2])

layout=Layout(
        yaxis=YAxis(title='Explained variance in percent'),
        title='Explained variance by different principal components')

fig = Figure(data=data, layout=layout)
py.iplot(fig)

<iframe id="igraph" scrolling="no" style="border:none;" seamless="seamless" src="https://plot.ly/~Mdipietro1990/34.embed" height="525px" width="100%"></iframe>

In [45]:
matrix_w = np.hstack((eig_pairs[0][1].reshape(4,1), 
                      eig_pairs[1][1].reshape(4,1)))

print('Matrix W:\n', matrix_w)

('Matrix W:\n', array([[ 0.19425661,  0.66868982],
       [-0.38056258,  0.69474323],
       [ 0.49778397,  0.26490302],
       [ 0.75475003,  0.00348642]]))


In [46]:
Y = X_std.dot(matrix_w)

In [47]:
Y

array([[ 0.55015685, -1.6136737 ],
       [ 0.07366462, -1.04974311],
       [-1.6996133 ,  1.34518358],
       [ 1.15619299,  1.40223121],
       [-1.52052125,  0.66300521],
       [ 1.00927268, -0.22723724],
       [-2.18990744, -0.80458283],
       [ 0.58679092,  0.34378259],
       [-0.50371035,  0.31860462],
       [ 2.76292466,  0.3817508 ],
       [ 0.11737639,  0.86789781],
       [-0.79597572,  0.63308369],
       [ 0.96492158,  1.70671266],
       [ 0.49541425, -1.40928887],
       [ 1.54358781, -2.0763401 ],
       [-0.57019243, -1.08000501],
       [-0.11508308, -0.01303923],
       [ 1.23696812, -0.71329621],
       [ 0.33758992, -2.35990192],
       [ 0.27373294,  0.17431205],
       [ 1.12327019, -0.11314443],
       [ 0.52536403, -0.20506791],
       [-1.04352681, -0.13871357],
       [ 1.26348895,  2.27542013],
       [ 0.29609048,  0.97875438],
       [ 0.07486087, -1.44773305],
       [ 0.66862756,  0.61638578],
       [-0.54461602, -0.05295681],
       [ 0.69217838,

In [48]:
from sklearn.feature_selection import VarianceThreshold
X = df
sel = VarianceThreshold(threshold=(.8 * (1 - .8)))
sel.fit_transform(X)

array([[-1.09591385e+00, -1.55146860e+00,  9.81895262e-01,
        -4.32870290e-01, -1.41133962e+00],
       [ 4.69964121e-01, -1.16655634e+00, -2.23213662e+00,
         5.86805000e-01,  2.17900763e-01],
       [ 9.53651680e-01,  1.51730410e+00, -1.79116439e+00,
        -6.13100992e-01, -7.37542337e-01],
       [ 2.06403827e+00, -6.01776606e-01,  1.67903212e+00,
        -3.83737464e-01,  4.50195441e-01],
       [-5.06758602e-01,  1.41616120e+00, -2.10586726e-01,
        -9.74257942e-01, -5.98301150e-01],
       [ 6.42621218e-01, -5.46306128e-01, -1.21811384e+00,
         1.40915812e+00,  7.41128118e-01],
       [-4.53286288e-01, -6.37167122e-01, -1.92941673e-01,
        -2.79227436e+00,  8.93092331e-01],
       [-3.91820523e-01,  4.36897891e-01,  1.06935242e+00,
         3.53748935e-01,  6.96252724e-01],
       [ 6.94606922e-01, -5.47417959e-03, -7.19469684e-01,
        -4.39744317e-01,  6.02034495e-01],
       [ 4.18969949e-01, -6.00016986e-01,  2.04524304e+00,
         1.73962183e+00